### ISSUE TITLE
Error: Unknown column

### ISSUE THREAD

**Issue by Caaine** [Hexer10/HexRedirect#2]
Failed to perform a query:
Errno: 1054
Error: Unknown column 'token' in 'where clause'

**Comment by Hexer10** [comment]
I'll try to run the server on a clean install this afternoon

**Comment by Hexer10** [comment]
By the way can you show me your database.cfg configuration? (Blanking out the sensitive data)

**Comment by Caaine** [comment]
Sourcemod: 1.10
MySQL: MariaDB 10.3

database.cfg:
 "hexredirect"
	{
		"driver"			"default"
		"host"				"89.163.xxx.xx"
		"database"			"redirect"
		"user"				"redirect"
		"pass"				"xXXxXXxxX"
            	//"timeout"                       "0"
            	"port"                          "5000"
	}

redirect.php:
$method = 'ip';
$host = '89.163.xxx.xx';
$username = 'redirect';
$password = 'xXXxXXxxX';
$dbname = 'redirect';
$port = 5000;

server.cfg:
sm_redirect_method "ip"

**Comment by Hexer10** [comment]
Please drop your table, and make the plugin create it again, if you still have issues regarded to this, please reply here

**Comment by Caaine** [comment]
when i type
"!steam" "https://steamcommunity.com/id/Caaine/"
i come to google not to my steam profil 

$homepage = 'https://www.google.com/';

**Comment by Hexer10** [comment]
After we've typed !steam in game do you get any replies? Mostly likely you'd like to change the homepage in the PHP script

**Comment by Caaine** [comment]
im chat
[SM] Redirecting to https://steamcommunity.com/id/Caaine/, just click on "server website" in the bottom left of the scoreboard.

and when i go on "server website" is google coming :S

**Comment by Hexer10** [comment]
Please check if both the game and the web server are using the same method ad well

**Comment by Caaine** [comment]
i tested the PR from kaganus and is working fine Oo
