### ISSUE TITLE
not working?

### ISSUE THREAD

**Issue by Caaine** [Hexer10/HexRedirect#6]
when i type !steam and open "server website"
in the URL https://mydomain.net/95.xX.xXX.xXx (my IP 95.xX.xXX.xXx) 
not more

mysql:
Token: MY IP
url: MY IP
time: 1545755357

**Comment by freakexeuLow** [comment]
@Hexer10 i try new version but i have the same problem "https://zeitzumkiffen.de/redirect/MYIP" 

[HexRedirect.smx] Failed to create table! Status code: 401, URL: https://zeitzumkiffen.de/redirect/redirect.php

**Comment by Hexer10** [comment]
It is not the same problem it means that the key set in the PHP config and the one set in the gameserver are different

**Comment by freakexeuLow** [comment]
@Hexer10 fixed, so now when i write !homepage or !forum and click on the Server Website Button, is that everytime google.com my error log is clear.
