### ISSUE TITLE
Web Script going to default page not the redirect page.

### ISSUE THREAD

**Issue by JamsRepos** [Hexer10/HexRedirect#7]
https://lubricantjam.com/uploads/2018/12/29/chrome_2018-12-29_00-47-45.jpg

Instantly typing !steam and then opening the Server Website still takes me to the default page, not the correct URL.

**Comment by Hexer10** [comment]
Please could you send me a pic of your database rows looks like? (ie from phpmyadmin, or a select from the terminal)

**Comment by JamsRepos** [comment]
> Please could you send me a pic of your database rows looks like? (ie from phpmyadmin, or a select from the terminal)

The URL above is the picture of my database rows, here's an updated version.

![Proof](https://lubricantjam.com/uploads/2018/12/29/chrome_2018-12-29_09-51-04.jpg)

**Comment by Hexer10** [comment]
I've just tested with both `steam` and `ip` and they work fine, make sure you've update both game files and web files (it seems the issue is there).
I'm on `1.21` version.

Also try to increase the expire time, and see what happens

**Comment by JamsRepos** [comment]
> I've just tested with both `steam` and `ip` and they work fine, make sure you've update both game files and web files (it seems the issue is there).
> I'm on `1.21` version.
> 
> Also try to increase the expire time, and see what happens

I made sure I updated my game server files however I am not confident in the web script, I shall check now for you. Sorry if this is the case.
